- hosts: centos
  tasks:

    - name: install web server
      yum: pkg=httpd state=present
      tags: install

    - name: install index page
      copy: src=front.html dest=/var/www/html/index.html backup=yes
      tags: configure
      notify: restart httpd

  handlers:
    - name: restart httpd
      service: name=httpd state=restarted

