---
- hosts: centos
  tasks:
    - name: Install http and php etc
      yum: name={{ item }} state=present
      with_items:  
        - httpd  
        - php  
        - php-mysql  
        - git  
        - libsemanage-python  
        - libselinux-python
